// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:connectly/models/phone_contact.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(PhoneContactAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(PhoneContactAdapter());
  }
}
